/*
 * 
 * 
 */
package vistas;

import java.awt.Color;
import java.awt.Menu;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import tp7.Alumno;
import tp7.Materia;

/**
 *
 * @author Marcel
 */
public class InscripcionEnMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form InscripcionEnMaterias
     */
    public InscripcionEnMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formMaterias = new javax.swing.JLabel();
        lblLegajo = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        btnInscribir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jComboMaterias = new javax.swing.JComboBox<>();
        jComboAlumno = new javax.swing.JComboBox<>();

        setClosable(true);
        setResizable(true);

        formMaterias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        formMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formMaterias.setText("Formulario de Inscripcion");
        formMaterias.setToolTipText("");

        lblLegajo.setText("ELIJA UNA MATERIA");

        lblApellido.setText("ELIJA UN ALUMNO");

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnSalir.setText("  Salir  ");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        for (HashMap.Entry cantidad: MenuColegio.listaMaterias.entrySet()) {
            jComboMaterias.addItem(cantidad.getValue().toString());
        }
        jComboMaterias.setSelectedItem(getActionMap());
        jComboMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMateriasActionPerformed(evt);
            }
        });

        for (HashMap.Entry cantidad: MenuColegio.listaAlumnos.entrySet()) {
            jComboAlumno.addItem(cantidad.getValue().toString());
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(formMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLegajo)
                    .addComponent(lblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnInscribir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboAlumno, javax.swing.GroupLayout.Alignment.LEADING, 0, 124, Short.MAX_VALUE)
                        .addComponent(jComboMaterias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLegajo)
                    .addComponent(jComboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(jComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnSalir))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMateriasActionPerformed

    }//GEN-LAST:event_jComboMateriasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        try{
            String materiaSeleccionada = jComboMaterias.getSelectedItem().toString();
            String alumnoSeleccionado =  jComboAlumno.getSelectedItem().toString();
            int idMateriaSeleccionada = 1;
            int idAlumnoSeleccionado = 0;
            for (HashMap.Entry entry : MenuColegio.listaMaterias.entrySet()){
                System.out.println(entry.getValue());
                if (entry.getValue().toString().equalsIgnoreCase(materiaSeleccionada)) {
                    idMateriaSeleccionada = (int) entry.getKey();
                    break;
                }
            }
            for (Map.Entry entry : MenuColegio.listaAlumnos.entrySet()) {
                if(entry.getValue().equals(alumnoSeleccionado)){
                    idAlumnoSeleccionado = (int) entry.getKey();
                    break;
                }
            }
            if(Alumno.materias.containsKey(idMateriaSeleccionada)&& {            
                JOptionPane.showMessageDialog(this,alumnoSeleccionado+" YA esta inscripto a: "+materiaSeleccionada);
            }else{
                Alumno.materias.put(idMateriaSeleccionada, materiaSeleccionada);
                JOptionPane.showMessageDialog(this, "El alumno "+alumnoSeleccionado+" "+ "se ha inscripto a: "+materiaSeleccionada);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Acción Inválida");
        }
    }//GEN-LAST:event_btnInscribirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel formMaterias;
    private javax.swing.JComboBox<String> jComboAlumno;
    private javax.swing.JComboBox<String> jComboMaterias;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblLegajo;
    // End of variables declaration//GEN-END:variables
}
