/*
 * 
 * 
 */
package vistas;

import tp7.Alumno;
import tp7.Materia;
import java.util.HashMap;

/**
 *
 * @author Marcel
 */
public class MenuColegio extends javax.swing.JFrame {
    public static HashMap<Integer,Materia> listaMaterias = new HashMap(); 
    public static HashMap<Integer,Alumno> listaAlumnos = new HashMap();

    /**
     * Creates new form NewJFrame
     */
    public MenuColegio() {
        initComponents();
        setBounds(300,90,800,600);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        callAltaMateria = new javax.swing.JMenuItem();
        callAltaAlumno = new javax.swing.JMenuItem();
        callFormInscrip = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu.setText("Menu");

        callAltaMateria.setText("Alta Materias");
        callAltaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callAltaMateriaActionPerformed(evt);
            }
        });
        jMenu.add(callAltaMateria);

        callAltaAlumno.setText("Alta Alumnos");
        callAltaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callAltaAlumnoActionPerformed(evt);
            }
        });
        jMenu.add(callAltaAlumno);

        callFormInscrip.setText("Inscripción en materias");
        callFormInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callFormInscripActionPerformed(evt);
            }
        });
        jMenu.add(callFormInscrip);

        jMenuBar1.add(jMenu);

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jMenuItemSalir.setText("Salir del sistema");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jSalir.add(jMenuItemSalir);

        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void callFormInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callFormInscripActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        InscripcionEnMaterias inscripMat = new InscripcionEnMaterias();
        inscripMat.setVisible(true);
        escritorio.add(inscripMat);
        escritorio.moveToFront(inscripMat);
    }//GEN-LAST:event_callFormInscripActionPerformed

    private void callAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callAltaMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AltaMaterias altaMat=new AltaMaterias();
        altaMat.setVisible(true);
        escritorio.add(altaMat);
        escritorio.moveToFront(altaMat);
    }//GEN-LAST:event_callAltaMateriaActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void callAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callAltaAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        AltaAlumnos altaAlum = new AltaAlumnos();
        altaAlum.setVisible(true);
        escritorio.add(altaAlum);
        escritorio.moveToFront(altaAlum);
       
    }//GEN-LAST:event_callAltaAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuColegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuColegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem callAltaAlumno;
    private javax.swing.JMenuItem callAltaMateria;
    private javax.swing.JMenuItem callFormInscrip;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jSalir;
    // End of variables declaration//GEN-END:variables
}
